### ISSUE TITLE
doesn't install properly on windows 10 x64

### ISSUE THREAD

**Issue by chris-cuc** [hyrious/glot#2]
1. installed package via Ctrl+Shift+P > install package > glot
2. Package installed successfully
3. Preferences > Package Settings > glot > Settings
4. Error message that it cannot locat res://Packages/glot/glot.sublime-settings
5. Preferences > Browse Packages...
6. %USERPROFILE%\AppData\Roaming\Sublime Text 3\Packages
7. There is no 'glot' folder. The only file anywhere in system with 'glot' in the name is  @ %USERPROFILE%\AppData\Roaming\Sublime Text 3\Installed Packages\Glot.sublime-package

Follow-up manual steps
> cd  %USERPROFILE%\AppData\Roaming\Sublime/ Text/ 3\Packages
> mkdir glot
> touch glot.sublime-settings
> cd ../User
> touch glot.sublime-settings
> cd User
> subl glot.sublime-settings
(insert {} and save file)

After manually creating the .sublime-settings files, I can now use Preferences > Package Settings > glot > Settings to open the settings file.

**Comment by hyrious** [comment]
added a `.no-sublime-package` to see if it could solve this issue

you can try it by uninstall glot then install it from github url
- - -
update:
now it(0.1.2) works but message `res://Packages/glot/glot.sublime-settings` still appears due to case-sensitive path. 😢 
so if you install it from Package Control, the new tag 0.1.3 will work well.
if you install it manually by git clone, I've renamed this repo, just delete and re-clone.

anyway, you should do a clean install (remove and install again) after the 0.1.3 online.

sorry for the issues.
