### ISSUE TITLE
glot doesn't work on windows 10

### ISSUE THREAD

**Issue by chris-cuc** [hyrious/glot#3]
After I manually forced glot to work (see previously logged issue), none of the glot commands work / do anything. In the sublime status bar, it says "unsupported language".

**Comment by hyrious** [comment]
the "unsupported language" issue should be fixed in 0.1.1.
you can try update your packages manually by ~~`Package Control: Upgrade Packages`~~ remove this package and install it again. the `Glot` folder should be created by Package Control.

I've pushed a new tag 0.1.3 that solves #2 and you can ~~wait for the refresh of packagecontrol~~ do a clean install now.
